# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_deploy.pct.py

__all__ = ['test_deploy_command_creates_systemd_unit', 'test_deploy_command_explicit_port_registered', 'test_deploy_command_failure_keeps_preexisting_port', 'test_deploy_command_failure_releases_new_port', 'test_deploy_command_nonroot_unit_runs_as_deploy_user', 'test_deploy_command_sets_status_active', 'test_deploy_command_with_env', 'test_deploy_command_with_meta', 'test_deploy_docker_compose_creates_systemd', 'test_deploy_dockerfile_builds_and_creates_compose', 'test_deploy_dockerfile_with_volumes', 'test_deploy_static_git_source', 'test_deploy_static_git_with_branch', 'test_deploy_static_registers_in_garden', 'test_deploy_static_sets_status_serving', 'test_deploy_static_subdirectory', 'test_deploy_static_subdomain', 'test_deploy_static_with_exclude', 'test_deploy_static_with_meta', 'test_deploy_static_without_meta', 'test_is_git_url_git_protocol', 'test_is_git_url_https', 'test_is_git_url_local_path', 'test_is_git_url_ssh', 'test_write_env_file_missing_file_warns', 'test_write_env_file_nothing_to_write_returns_none', 'test_write_env_file_precedence']

# %% pts/tests/test_deploy.pct.py 3
import json
from unittest.mock import MagicMock, patch, call

import pytest

from appgarden.config import ServerConfig
from appgarden.deploy import (
    is_git_url,
    deploy_static,
    deploy_command,
    deploy_docker_compose,
    deploy_dockerfile,
    upload_source,
    _app_dir,
    _source_dir,
    _write_env_file,
)

# %% pts/tests/test_deploy.pct.py 5
def test_is_git_url_https():
    """HTTPS git URLs are detected."""
    assert is_git_url("https://github.com/user/repo.git") is True
    assert is_git_url("https://github.com/user/repo") is True

# %% pts/tests/test_deploy.pct.py 6
def test_is_git_url_ssh():
    """SSH git URLs are detected."""
    assert is_git_url("git@github.com:user/repo.git") is True

# %% pts/tests/test_deploy.pct.py 7
def test_is_git_url_git_protocol():
    """git:// protocol URLs are detected."""
    assert is_git_url("git://example.com/repo.git") is True

# %% pts/tests/test_deploy.pct.py 8
def test_is_git_url_local_path():
    """Local paths are not git URLs."""
    assert is_git_url("/home/user/project") is False
    assert is_git_url("./my-site") is False
    assert is_git_url("../build") is False

# %% pts/tests/test_deploy.pct.py 10
def _make_server():
    return ServerConfig(
        ssh_user="root", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
    )

# %% pts/tests/test_deploy.pct.py 11
def _mock_host():
    """Create a mock host with standard return values."""
    host = MagicMock()

    def _mock_run(command="", **kw):
        import hashlib
        output = MagicMock()
        # CAS writes (locked compare-and-swap update) always succeed
        if "CAS_OK" in command:
            output.stdout = "CAS_OK"
        # Locked reads: sha + content of the requested state file
        elif ("flock" in command and "cat" in command) or "sha256sum" in command:
            if "ports.json" in command:
                payload = json.dumps({"next_port": 10000, "allocated": {}})
            elif "garden.json" in command:
                payload = json.dumps({"apps": {}})
            else:
                payload = ""
            if "sha256sum" in command:
                sha = hashlib.sha256(payload.encode()).hexdigest()
                output.stdout = f"{sha}\n{payload}"
            else:
                output.stdout = payload
        else:
            output.stdout = ""
        return (True, output)

    host.run_shell_command.side_effect = _mock_run
    host.put_file.return_value = True

    def _mock_get(remote_filename, filename_or_io, **kw):
        if "ports.json" in remote_filename:
            data = {"next_port": 10000, "allocated": {}}
        else:
            data = {"apps": {}}
        filename_or_io.write(json.dumps(data).encode("utf-8"))
        return True

    host.get_file.side_effect = _mock_get
    return host

# %% pts/tests/test_deploy.pct.py 12
def test_deploy_static_subdomain():
    """deploy_static uploads source, writes Caddy config, and registers app."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory") as mock_upload:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(_make_server(), "mysite", "/tmp/site", "mysite.apps.example.com")

    # Should have uploaded the directory
    mock_upload.assert_called_once()

    # Collect all written files
    written = {}
    for c in host.put_file.call_args_list:
        path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[path] = bio.getvalue().decode("utf-8")

    # Should have written a Caddy config
    caddy_files = [p for p in written if ".caddy" in p]
    assert len(caddy_files) == 1
    caddy_content = written[caddy_files[0]]
    assert "mysite.apps.example.com" in caddy_content
    assert "file_server" in caddy_content

    # Should have written garden.json
    garden_files = [p for p in written if "garden.json" in p]
    assert len(garden_files) == 1
    garden = json.loads(written[garden_files[0]])
    assert "mysite" in garden["apps"]
    assert garden["apps"]["mysite"]["method"] == "static"
    assert garden["apps"]["mysite"]["url"] == "mysite.apps.example.com"

    # Should have written app.json
    app_json_files = [p for p in written if "app.json" in p]
    assert len(app_json_files) == 1

# %% pts/tests/test_deploy.pct.py 13
def test_deploy_static_subdirectory():
    """deploy_static with subdirectory URL creates correct routing."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory") as mock_upload:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(_make_server(), "docs", "/tmp/docs", "apps.example.com/docs")

    written = {}
    for c in host.put_file.call_args_list:
        path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[path] = bio.getvalue().decode("utf-8")

    # Check garden.json has subdirectory routing
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["docs"]["routing"] == "subdirectory"

    # Caddy config should use handle_path
    caddy_files = [p for p in written if ".caddy" in p]
    assert len(caddy_files) == 1
    caddy_content = written[caddy_files[0]]
    assert "handle_path /docs/*" in caddy_content

# %% pts/tests/test_deploy.pct.py 14
def test_deploy_static_git_source():
    """deploy_static with git URL clones instead of uploading."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(
            _make_server(), "mysite",
            "https://github.com/user/site.git",
            "mysite.apps.example.com",
        )

    # Should have run git clone
    cmds = [c.kwargs.get("command", "") for c in host.run_shell_command.call_args_list]
    assert any("git clone" in c for c in cmds), "Should git clone the source"

    # Check garden state records source_type=git
    written = {}
    for c in host.put_file.call_args_list:
        path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[path] = bio.getvalue().decode("utf-8")

    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["mysite"]["source_type"] == "git"

# %% pts/tests/test_deploy.pct.py 15
def test_deploy_static_git_with_branch():
    """deploy_static with git URL and branch passes -b flag."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(
            _make_server(), "mysite",
            "https://github.com/user/site.git",
            "mysite.apps.example.com",
            branch="gh-pages",
        )

    cmds = [c.kwargs.get("command", "") for c in host.run_shell_command.call_args_list]
    clone_cmds = [c for c in cmds if "git clone" in c]
    assert len(clone_cmds) == 1
    assert "-b" in clone_cmds[0] and "gh-pages" in clone_cmds[0]

# %% pts/tests/test_deploy.pct.py 16
def test_deploy_static_registers_in_garden():
    """deploy_static writes app entry to garden.json with correct fields."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(_make_server(), "blog", "/tmp/blog", "blog.apps.example.com")

    # Find the garden.json write
    written = {}
    for c in host.put_file.call_args_list:
        path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[path] = bio.getvalue().decode("utf-8")

    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])

    app = garden["apps"]["blog"]
    assert app["name"] == "blog"
    assert app["method"] == "static"
    assert app["url"] == "blog.apps.example.com"
    assert app["routing"] == "subdomain"
    assert app["source_type"] == "local"
    assert "created_at" in app
    assert "updated_at" in app

# %% pts/tests/test_deploy.pct.py 18
def _get_written_files(host):
    """Extract all files written via put_file on a mock host."""
    written = {}
    for c in host.put_file.call_args_list:
        path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[path] = bio.getvalue().decode("utf-8")
    return written

# %% pts/tests/test_deploy.pct.py 20
def _stateful_host(garden_state=None, ports_state=None):
    """Mock host whose CAS updates actually apply to an in-memory state, so
    tests can assert final registry/garden contents after multi-step flows."""
    import hashlib
    import re as _re

    state = {
        "garden": garden_state or {"apps": {}},
        "ports": ports_state or {"next_port": 10000, "allocated": {}},
    }
    staged: dict[str, str] = {}
    host = MagicMock()

    def _key(cmd):
        return "ports" if "ports.json" in cmd else "garden"

    def _run(command="", **kw):
        out = MagicMock(); out.stderr = ""
        if "CAS_OK" in command:
            m = _re.search(r"mv (\S+\.tmp\.[0-9a-f]{8})", command)
            if m and m.group(1) in staged:
                state[_key(command)] = json.loads(staged[m.group(1)])
            out.stdout = "CAS_OK"
            return (True, out)
        if "sha256sum" in command:
            payload = json.dumps(state[_key(command)])
            out.stdout = hashlib.sha256(payload.encode()).hexdigest() + "\n" + payload
            return (True, out)
        out.stdout = ""
        return (True, out)

    host.run_shell_command.side_effect = _run

    def _put(filename_or_io, remote_filename, **kw):
        staged[remote_filename] = filename_or_io.getvalue().decode("utf-8")
        return True
    host.put_file.side_effect = _put

    def _get(remote_filename, filename_or_io, **kw):
        if remote_filename.endswith(".caddy"):
            raise FileNotFoundError(remote_filename)
        data = state["ports"] if "ports.json" in remote_filename else state["garden"]
        filename_or_io.write(json.dumps(data).encode("utf-8"))
        return True
    host.get_file.side_effect = _get

    host._state = state
    return host

# %% pts/tests/test_deploy.pct.py 21
def test_deploy_command_explicit_port_registered():
    """An explicit --port lands in the shared registry (idempotently), so later
    auto-allocations can't hand it out to another app."""
    host = _stateful_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        deploy_command(_make_server(), "myapp", "python app.py",
                       "myapp.apps.example.com", port=10500, source="/tmp/src")

    assert host._state["ports"]["allocated"]["10500"] == "myapp"
    assert host._state["ports"]["next_port"] == 10501
    assert host._state["garden"]["apps"]["myapp"]["port"] == 10500

# %% pts/tests/test_deploy.pct.py 22
def test_deploy_command_failure_releases_new_port():
    """A newly-claimed port is released when a later deploy step fails —
    otherwise the allocation leaks and nothing can ever reap it."""
    host = _stateful_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"), \
         patch("appgarden.deploy.deploy_caddy_config", side_effect=RuntimeError("caddy exploded")):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        with pytest.raises(RuntimeError, match="caddy exploded"):
            deploy_command(_make_server(), "myapp", "python app.py",
                           "myapp.apps.example.com", source="/tmp/src")

    assert host._state["ports"]["allocated"] == {}
    assert "myapp" not in host._state["garden"]["apps"]

# %% pts/tests/test_deploy.pct.py 23
def test_deploy_command_failure_keeps_preexisting_port():
    """A failed redeploy must NOT release the port the running app already
    holds — only newly-created claims are unwound."""
    host = _stateful_host(ports_state={"next_port": 10001, "allocated": {"10000": "myapp"}})

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"), \
         patch("appgarden.deploy.deploy_caddy_config", side_effect=RuntimeError("caddy exploded")):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        with pytest.raises(RuntimeError, match="caddy exploded"):
            deploy_command(_make_server(), "myapp", "python app.py",
                           "myapp.apps.example.com", source="/tmp/src")

    assert host._state["ports"]["allocated"] == {"10000": "myapp"}

# %% pts/tests/test_deploy.pct.py 25
def test_deploy_command_creates_systemd_unit():
    """deploy_command creates a systemd unit with PORT env var."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_command(
            _make_server(), "myapp", "python app.py",
            "myapp.apps.example.com", source="/tmp/src",
        )

    written = _get_written_files(host)

    # Should have a systemd unit
    unit_files = [p for p in written if p.endswith(".service")]
    assert len(unit_files) == 1
    unit_content = written[unit_files[0]]
    assert "python app.py" in unit_content
    assert '"PORT=10000"' in unit_content

    # Should have registered with method=command
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["myapp"]["method"] == "command"
    assert garden["apps"]["myapp"]["port"] == 10000

    # Root deploy: no User= directive (runs as root, matching its file ownership)
    assert "User=" not in unit_content

# %% pts/tests/test_deploy.pct.py 26
def test_deploy_command_nonroot_unit_runs_as_deploy_user():
    """A non-root deploy renders User=<ssh_user> into the unit so the app
    process doesn't run as root (issue #22)."""
    host = _mock_host()
    server = ServerConfig(
        ssh_user="deploy", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
    )

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_command(server, "myapp", "python app.py",
                       "myapp.apps.example.com", source="/tmp/src")

    written = _get_written_files(host)
    # Non-root units are staged via the privileged wrapper's tmp path
    unit_files = [p for p in written
                  if p.endswith(".service") or p.startswith("/tmp/appgarden-unit-")]
    assert unit_files, f"no unit content captured; wrote: {list(written)}"
    unit_content = written[unit_files[0]]
    assert "User=deploy\n" in unit_content

# %% pts/tests/test_deploy.pct.py 27
def test_deploy_command_with_env():
    """deploy_command writes .env file with correct permissions."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_command(
            _make_server(), "myapp", "node server.js",
            "myapp.apps.example.com",
            env_vars={"SECRET": "abc123"},
        )

    written = _get_written_files(host)

    # Should have written .env file
    env_files = [p for p in written if p.endswith("/.env")]
    assert len(env_files) == 1
    assert 'SECRET="abc123"' in written[env_files[0]]

    # Should have created file with restrictive permissions
    cmds = [c.kwargs.get("command", "") for c in host.run_shell_command.call_args_list]
    assert any("install -m 600" in c for c in cmds)

# %% pts/tests/test_deploy.pct.py 29
def test_deploy_docker_compose_creates_systemd():
    """deploy_docker_compose creates systemd unit with docker compose up."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_docker_compose(
            _make_server(), "mystack", "/tmp/compose-project",
            "mystack.apps.example.com",
        )

    written = _get_written_files(host)

    unit_files = [p for p in written if p.endswith(".service")]
    assert len(unit_files) == 1
    unit_content = written[unit_files[0]]
    assert "docker compose up" in unit_content
    assert "docker compose down" in unit_content
    assert "docker.service" in unit_content

    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["mystack"]["method"] == "docker-compose"

# %% pts/tests/test_deploy.pct.py 31
def test_deploy_dockerfile_builds_and_creates_compose():
    """deploy_dockerfile builds image and generates docker-compose.yml."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_dockerfile(
            _make_server(), "webapp", "/tmp/app",
            "webapp.apps.example.com",
            container_port=8080,
        )

    # Should have run docker build
    cmds = [c.kwargs.get("command", "") for c in host.run_shell_command.call_args_list]
    assert any("docker build" in c and "appgarden-webapp" in c for c in cmds)

    written = _get_written_files(host)

    # Should have generated docker-compose.yml with image reference
    compose_files = [p for p in written if "docker-compose.yml" in p]
    assert len(compose_files) == 1
    compose_content = written[compose_files[0]]
    assert "appgarden-webapp" in compose_content
    assert "10000:8080" in compose_content

    # Should register with method=dockerfile
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["webapp"]["method"] == "dockerfile"
    assert garden["apps"]["webapp"]["container_port"] == 8080

# %% pts/tests/test_deploy.pct.py 33
def test_deploy_static_with_meta():
    """deploy_static passes meta through to garden.json via _register_app."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(
            _make_server(), "mysite", "/tmp/site",
            "mysite.apps.example.com",
            extra={"meta": {"team": "frontend", "tier": "free"}},
        )

    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["mysite"]["meta"] == {"team": "frontend", "tier": "free"}

# %% pts/tests/test_deploy.pct.py 34
def test_deploy_static_without_meta():
    """deploy_static without meta does not add a meta key."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(_make_server(), "mysite", "/tmp/site", "mysite.apps.example.com")

    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert "meta" not in garden["apps"]["mysite"]

# %% pts/tests/test_deploy.pct.py 35
def test_deploy_command_with_meta():
    """deploy_command passes meta through to garden.json."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_command(
            _make_server(), "myapp", "python app.py",
            "myapp.apps.example.com",
            extra={"meta": {"visibility": "internal"}},
        )

    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["myapp"]["meta"] == {"visibility": "internal"}

# %% pts/tests/test_deploy.pct.py 37
def test_deploy_static_sets_status_serving():
    """deploy_static sets status to 'serving' in garden.json."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(_make_server(), "mysite", "/tmp/site", "mysite.apps.example.com")

    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["mysite"]["status"] == "serving"

# %% pts/tests/test_deploy.pct.py 38
def test_deploy_command_sets_status_active():
    """deploy_command sets status to 'active' in garden.json."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_command(
            _make_server(), "myapp", "python app.py",
            "myapp.apps.example.com",
        )

    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["myapp"]["status"] == "active"

# %% pts/tests/test_deploy.pct.py 39
def test_deploy_dockerfile_with_volumes():
    """deploy_dockerfile passes volumes to docker-compose.yml and stores in garden.json."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_dockerfile(
            _make_server(), "webapp", "/tmp/app",
            "webapp.apps.example.com",
            volumes=["./data:/app/data", "/var/logs:/app/logs:ro"],
        )

    written = _get_written_files(host)

    # docker-compose.yml should contain the volume mounts
    compose_files = [p for p in written if "docker-compose.yml" in p]
    assert len(compose_files) == 1
    compose_content = written[compose_files[0]]
    assert "./data:/app/data" in compose_content
    assert "/var/logs:/app/logs:ro" in compose_content

    # garden.json should store the volumes
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["webapp"]["volumes"] == ["./data:/app/data", "/var/logs:/app/logs:ro"]

# %% pts/tests/test_deploy.pct.py 40
def test_deploy_static_with_exclude():
    """deploy_static passes exclude/gitignore to rsync and stores in garden.json."""
    host = _mock_host()

    with patch("appgarden.deploy.ssh_connect") as mock_connect, \
         patch("appgarden.deploy.upload_directory") as mock_upload:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)

        deploy_static(
            _make_server(), "mysite", "/tmp/site",
            "mysite.apps.example.com",
            exclude=["node_modules", ".env"],
            gitignore=False,
        )

    # upload_directory should have been called with exclude and gitignore
    mock_upload.assert_called_once()
    call_kwargs = mock_upload.call_args
    assert call_kwargs.kwargs.get("exclude") == ["node_modules", ".env"]
    assert call_kwargs.kwargs.get("gitignore") is False

    # garden.json should have exclude and gitignore stored
    written = _get_written_files(host)
    garden_files = [p for p in written if "garden.json" in p]
    garden = json.loads(written[garden_files[0]])
    assert garden["apps"]["mysite"]["exclude"] == ["node_modules", ".env"]
    assert garden["apps"]["mysite"]["gitignore"] is False

# %% pts/tests/test_deploy.pct.py 42
def test_write_env_file_precedence(tmp_path):
    """Layering is env_vars < env_file < env_overrides — the .env file is
    line-based last-wins, so later sections must appear after earlier ones."""
    envf = tmp_path / "envfile"
    envf.write_text('B="from-file"\nC="from-file"\n')
    host = _mock_host()

    path = _write_env_file(host, "myapp",
                           env_vars={"A": "config", "B": "config"},
                           env_file=str(envf),
                           env_overrides={"C": "cli"})
    assert path.endswith("/myapp/.env")

    written = _get_written_files(host)
    content = next(v for k, v in written.items() if k.endswith("/.env"))
    # env_file overrides toml env...
    assert content.rindex('B="from-file"') > content.rindex('B="config"')
    # ...and CLI overrides both
    assert content.rindex('C="cli"') > content.rindex('C="from-file"')
    assert 'A="config"' in content

# %% pts/tests/test_deploy.pct.py 43
def test_write_env_file_missing_file_warns(capsys):
    """A missing env_file warns (and deploys without it) rather than failing
    silently — the warning names the resolved path."""
    host = _mock_host()
    _write_env_file(host, "myapp", env_vars={"A": "1"},
                    env_file="/nonexistent/appgarden-env-xyz")
    out = capsys.readouterr().out
    assert "env_file not found" in out

# %% pts/tests/test_deploy.pct.py 44
def test_write_env_file_nothing_to_write_returns_none():
    host = _mock_host()
    assert _write_env_file(host, "myapp") is None
    host.put_file.assert_not_called()
