# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_ports.pct.py

__all__ = ['test_allocate_after_release', 'test_allocate_duplicate_app_returns_existing', 'test_allocate_first_port', 'test_allocate_increments', 'test_empty_ports_state', 'test_merge_allocations_adds_and_advances', 'test_merge_allocations_idempotent', 'test_merge_allocations_preserves_existing', 'test_port_funcs_share_one_registry', 'test_register_port', 'test_register_port_advances_next', 'test_register_port_below_next', 'test_register_port_conflict', 'test_register_port_same_app_idempotent', 'test_release_nonexistent_raises', 'test_release_port']

# %% pts/tests/test_ports.pct.py 3
import pytest

import appgarden.ports as ports_mod
from appgarden.ports import (
    PORT_RANGE_START,
    empty_ports_state,
    _allocate_port,
    _release_port,
    _register_port,
    merge_allocations,
    allocate_port,
    release_port,
    get_app_port,
)

# %% pts/tests/test_ports.pct.py 5
def test_empty_ports_state():
    """Fresh state starts at PORT_RANGE_START with no allocations."""
    ports = empty_ports_state()
    assert ports["next_port"] == PORT_RANGE_START
    assert ports["allocated"] == {}

# %% pts/tests/test_ports.pct.py 7
def test_allocate_first_port():
    """First allocation returns PORT_RANGE_START."""
    ports = empty_ports_state()
    ports, port = _allocate_port(ports, "myapp")
    assert port == PORT_RANGE_START
    assert ports["allocated"][str(PORT_RANGE_START)] == "myapp"
    assert ports["next_port"] == PORT_RANGE_START + 1

# %% pts/tests/test_ports.pct.py 8
def test_allocate_increments():
    """Successive allocations produce incrementing ports."""
    ports = empty_ports_state()
    ports, p1 = _allocate_port(ports, "app1")
    ports, p2 = _allocate_port(ports, "app2")
    ports, p3 = _allocate_port(ports, "app3")
    assert p1 == PORT_RANGE_START
    assert p2 == PORT_RANGE_START + 1
    assert p3 == PORT_RANGE_START + 2

# %% pts/tests/test_ports.pct.py 9
def test_allocate_duplicate_app_returns_existing():
    """Allocating twice for the same app returns the existing port."""
    ports = empty_ports_state()
    ports, p1 = _allocate_port(ports, "myapp")
    ports, p2 = _allocate_port(ports, "myapp")
    assert p1 == p2
    assert ports["next_port"] == PORT_RANGE_START + 1  # not incremented again

# %% pts/tests/test_ports.pct.py 11
def test_release_port():
    """Releasing a port removes it from allocated."""
    ports = empty_ports_state()
    ports, port = _allocate_port(ports, "myapp")
    ports = _release_port(ports, "myapp")
    assert str(port) not in ports["allocated"]

# %% pts/tests/test_ports.pct.py 12
def test_release_nonexistent_raises():
    """Releasing a port for an unknown app raises ValueError."""
    ports = empty_ports_state()
    with pytest.raises(ValueError, match="No port allocated"):
        _release_port(ports, "ghost")

# %% pts/tests/test_ports.pct.py 13
def test_allocate_after_release():
    """After release, new allocations still increment (no reuse)."""
    ports = empty_ports_state()
    ports, p1 = _allocate_port(ports, "app1")
    ports, p2 = _allocate_port(ports, "app2")
    ports = _release_port(ports, "app1")
    ports, p3 = _allocate_port(ports, "app3")
    assert p3 == PORT_RANGE_START + 2  # next_port continues from 2

# %% pts/tests/test_ports.pct.py 15
def test_register_port():
    """Register a specific port for an app."""
    ports = empty_ports_state()
    ports = _register_port(ports, 8080, "custom")
    assert ports["allocated"]["8080"] == "custom"

# %% pts/tests/test_ports.pct.py 16
def test_register_port_conflict():
    """Registering an already-used port raises ValueError."""
    ports = empty_ports_state()
    ports = _register_port(ports, 8080, "first")
    with pytest.raises(ValueError, match="already allocated"):
        _register_port(ports, 8080, "second")

# %% pts/tests/test_ports.pct.py 17
def test_register_port_same_app_idempotent():
    """Re-registering the same port for the same app is a no-op (a redeploy
    with an explicit port must not conflict with itself)."""
    ports = empty_ports_state()
    ports = _register_port(ports, 8080, "app")
    ports = _register_port(ports, 8080, "app")
    assert ports["allocated"]["8080"] == "app"

# %% pts/tests/test_ports.pct.py 18
def test_register_port_advances_next():
    """Registering a port >= next_port advances next_port."""
    ports = empty_ports_state()
    ports = _register_port(ports, 10005, "app")
    assert ports["next_port"] == 10006

# %% pts/tests/test_ports.pct.py 19
def test_register_port_below_next():
    """Registering a port below next_port doesn't change next_port."""
    ports = {"next_port": 10010, "allocated": {}}
    ports = _register_port(ports, 10005, "app")
    assert ports["next_port"] == 10010

# %% pts/tests/test_ports.pct.py 21
def test_merge_allocations_adds_and_advances():
    """Merging app ports records them and advances next_port past the highest."""
    ports = empty_ports_state()
    merged = merge_allocations(ports, {10000: "web", 10005: "api"})
    assert merged["allocated"] == {"10000": "web", "10005": "api"}
    assert merged["next_port"] == 10006
    # Original is not mutated
    assert ports == empty_ports_state()

# %% pts/tests/test_ports.pct.py 22
def test_merge_allocations_idempotent():
    """Re-merging the same allocations is a no-op (safe to run on every init)."""
    ports = empty_ports_state()
    once = merge_allocations(ports, {10000: "web"})
    twice = merge_allocations(once, {10000: "web"})
    assert once == twice
    assert twice["allocated"] == {"10000": "web"}
    assert twice["next_port"] == 10001

# %% pts/tests/test_ports.pct.py 23
def test_merge_allocations_preserves_existing():
    """Existing allocations survive; a lower-numbered merge doesn't lower next_port."""
    ports = {"next_port": 10010, "allocated": {"10009": "old"}}
    merged = merge_allocations(ports, {10001: "new"})
    assert merged["allocated"] == {"10009": "old", "10001": "new"}
    assert merged["next_port"] == 10010

# %% pts/tests/test_ports.pct.py 25
def test_port_funcs_share_one_registry(monkeypatch):
    """All gardens allocate from a single store, so ports never collide across them."""
    # One in-memory store standing in for the single host-level ports.json.
    store = {"state": empty_ports_state()}

    def fake_update_locked(host, mutate):
        store["state"] = mutate(store["state"])
        return store["state"]

    def fake_read(host):
        return store["state"]

    monkeypatch.setattr(ports_mod, "update_ports_state_locked", fake_update_locked)
    monkeypatch.setattr(ports_mod, "read_ports_state", fake_read)

    # Two apps deployed from different gardens draw from the same counter.
    p_a = allocate_port(None, "app-a")
    p_b = allocate_port(None, "app-b")
    assert p_a != p_b
    assert store["state"]["allocated"] == {str(p_a): "app-a", str(p_b): "app-b"}

    # get_app_port and release_port operate on the same shared registry.
    assert get_app_port(None, "app-a") == p_a
    release_port(None, "app-a")
    assert store["state"]["allocated"] == {str(p_b): "app-b"}
    assert get_app_port(None, "app-a") is None
