# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_ports.pct.py

__all__ = ['test_allocate_after_release', 'test_allocate_duplicate_app_raises', 'test_allocate_first_port', 'test_allocate_increments', 'test_empty_ports_state', 'test_register_port', 'test_register_port_advances_next', 'test_register_port_below_next', 'test_register_port_conflict', 'test_release_nonexistent_raises', 'test_release_port']

# %% pts/tests/test_ports.pct.py 3
import pytest

from appgarden.ports import (
    PORT_RANGE_START,
    empty_ports_state,
    _allocate_port,
    _release_port,
    _register_port,
)

# %% pts/tests/test_ports.pct.py 5
def test_empty_ports_state():
    """Fresh state starts at PORT_RANGE_START with no allocations."""
    ports = empty_ports_state()
    assert ports["next_port"] == PORT_RANGE_START
    assert ports["allocated"] == {}

# %% pts/tests/test_ports.pct.py 7
def test_allocate_first_port():
    """First allocation returns PORT_RANGE_START."""
    ports = empty_ports_state()
    ports, port = _allocate_port(ports, "myapp")
    assert port == PORT_RANGE_START
    assert ports["allocated"][str(PORT_RANGE_START)] == "myapp"
    assert ports["next_port"] == PORT_RANGE_START + 1

# %% pts/tests/test_ports.pct.py 8
def test_allocate_increments():
    """Successive allocations produce incrementing ports."""
    ports = empty_ports_state()
    ports, p1 = _allocate_port(ports, "app1")
    ports, p2 = _allocate_port(ports, "app2")
    ports, p3 = _allocate_port(ports, "app3")
    assert p1 == PORT_RANGE_START
    assert p2 == PORT_RANGE_START + 1
    assert p3 == PORT_RANGE_START + 2

# %% pts/tests/test_ports.pct.py 9
def test_allocate_duplicate_app_raises():
    """Allocating twice for the same app raises ValueError."""
    ports = empty_ports_state()
    ports, _ = _allocate_port(ports, "myapp")
    with pytest.raises(ValueError, match="already has port"):
        _allocate_port(ports, "myapp")

# %% pts/tests/test_ports.pct.py 11
def test_release_port():
    """Releasing a port removes it from allocated."""
    ports = empty_ports_state()
    ports, port = _allocate_port(ports, "myapp")
    ports = _release_port(ports, "myapp")
    assert str(port) not in ports["allocated"]

# %% pts/tests/test_ports.pct.py 12
def test_release_nonexistent_raises():
    """Releasing a port for an unknown app raises ValueError."""
    ports = empty_ports_state()
    with pytest.raises(ValueError, match="No port allocated"):
        _release_port(ports, "ghost")

# %% pts/tests/test_ports.pct.py 13
def test_allocate_after_release():
    """After release, new allocations still increment (no reuse)."""
    ports = empty_ports_state()
    ports, p1 = _allocate_port(ports, "app1")
    ports, p2 = _allocate_port(ports, "app2")
    ports = _release_port(ports, "app1")
    ports, p3 = _allocate_port(ports, "app3")
    assert p3 == PORT_RANGE_START + 2  # next_port continues from 2

# %% pts/tests/test_ports.pct.py 15
def test_register_port():
    """Register a specific port for an app."""
    ports = empty_ports_state()
    ports = _register_port(ports, 8080, "custom")
    assert ports["allocated"]["8080"] == "custom"

# %% pts/tests/test_ports.pct.py 16
def test_register_port_conflict():
    """Registering an already-used port raises ValueError."""
    ports = empty_ports_state()
    ports = _register_port(ports, 8080, "first")
    with pytest.raises(ValueError, match="already allocated"):
        _register_port(ports, 8080, "second")

# %% pts/tests/test_ports.pct.py 17
def test_register_port_advances_next():
    """Registering a port >= next_port advances next_port."""
    ports = empty_ports_state()
    ports = _register_port(ports, 10005, "app")
    assert ports["next_port"] == 10006

# %% pts/tests/test_ports.pct.py 18
def test_register_port_below_next():
    """Registering a port below next_port doesn't change next_port."""
    ports = {"next_port": 10010, "allocated": {}}
    ports = _register_port(ports, 10005, "app")
    assert ports["next_port"] == 10010
