# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_auto_docker.pct.py

__all__ = ['test_deploy_auto_local_detection', 'test_deploy_auto_no_runtime_detected', 'test_deploy_auto_remote_detection_and_register', 'test_detect_go', 'test_detect_nodejs', 'test_detect_priority', 'test_detect_python_pip', 'test_detect_python_pyproject', 'test_detect_ruby', 'test_detect_rust', 'test_detect_unknown', 'test_generate_dockerfile_custom_setup', 'test_generate_dockerfile_nodejs', 'test_generate_dockerfile_python', 'test_infer_setup_nodejs', 'test_infer_setup_python']

# %% pts/tests/test_auto_docker.pct.py 3
from pathlib import Path

from appgarden.auto_docker import (
    detect_runtime, infer_setup_command, generate_dockerfile,
    Runtime, RUNTIMES,
)

# %% pts/tests/test_auto_docker.pct.py 5
def test_detect_nodejs(tmp_path):
    """Detect Node.js from package.json."""
    (tmp_path / "package.json").write_text("{}")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "nodejs"
    assert "node" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 6
def test_detect_python_pip(tmp_path):
    """Detect Python (pip) from requirements.txt."""
    (tmp_path / "requirements.txt").write_text("flask\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "python-pip"
    assert "python" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 7
def test_detect_python_pyproject(tmp_path):
    """Detect Python from pyproject.toml."""
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'myapp'\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "python"

# %% pts/tests/test_auto_docker.pct.py 8
def test_detect_go(tmp_path):
    """Detect Go from go.mod."""
    (tmp_path / "go.mod").write_text("module example.com/app\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "go"
    assert "golang" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 9
def test_detect_ruby(tmp_path):
    """Detect Ruby from Gemfile."""
    (tmp_path / "Gemfile").write_text('source "https://rubygems.org"\n')
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "ruby"

# %% pts/tests/test_auto_docker.pct.py 10
def test_detect_rust(tmp_path):
    """Detect Rust from Cargo.toml."""
    (tmp_path / "Cargo.toml").write_text("[package]\nname = 'app'\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "rust"

# %% pts/tests/test_auto_docker.pct.py 11
def test_detect_unknown(tmp_path):
    """Unknown project returns None."""
    (tmp_path / "main.c").write_text("int main() {}\n")
    rt = detect_runtime(tmp_path)
    assert rt is None

# %% pts/tests/test_auto_docker.pct.py 12
def test_detect_priority(tmp_path):
    """package.json takes priority over pyproject.toml."""
    (tmp_path / "package.json").write_text("{}")
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "nodejs"

# %% pts/tests/test_auto_docker.pct.py 14
def test_infer_setup_nodejs():
    """Node.js setup is npm install."""
    rt = Runtime(name="nodejs", base_image="node:22", setup_cmd="npm install")
    assert infer_setup_command(rt) == "npm install"

# %% pts/tests/test_auto_docker.pct.py 15
def test_infer_setup_python():
    """Python setup is pip install."""
    rt = Runtime(name="python-pip", base_image="python:3.12",
                 setup_cmd="pip install -r requirements.txt")
    assert "pip install" in infer_setup_command(rt)

# %% pts/tests/test_auto_docker.pct.py 17
def test_generate_dockerfile_nodejs():
    """Generated Dockerfile for Node.js has correct structure."""
    rt = Runtime(name="nodejs", base_image="node:22",
                 setup_cmd="npm install", copy_first="package*.json")
    content = generate_dockerfile(rt, container_port=3000, cmd='["node", "server.js"]')
    assert "FROM node:22" in content
    assert "COPY package*.json ." in content
    assert "RUN npm install" in content
    assert "EXPOSE 3000" in content
    assert '["node", "server.js"]' in content

# %% pts/tests/test_auto_docker.pct.py 18
def test_generate_dockerfile_custom_setup():
    """Custom setup_cmd overrides the runtime default."""
    rt = Runtime(name="nodejs", base_image="node:22",
                 setup_cmd="npm install", copy_first="package*.json")
    content = generate_dockerfile(
        rt, container_port=8080, cmd="npm start",
        setup_cmd="npm ci --production",
    )
    assert "RUN npm ci --production" in content
    assert "npm install" not in content

# %% pts/tests/test_auto_docker.pct.py 19
def test_generate_dockerfile_python():
    """Generated Dockerfile for Python has correct structure."""
    rt = Runtime(name="python-pip", base_image="python:3.12",
                 setup_cmd="pip install -r requirements.txt",
                 copy_first="requirements.txt")
    content = generate_dockerfile(rt, container_port=5000, cmd="python app.py")
    assert "FROM python:3.12" in content
    assert "COPY requirements.txt ." in content
    assert "RUN pip install -r requirements.txt" in content
    assert "EXPOSE 5000" in content

# %% pts/tests/test_auto_docker.pct.py 21
import json
from unittest.mock import MagicMock, patch

import pytest

from appgarden.auto_docker import deploy_auto
from appgarden.config import ServerConfig
from test_deploy import _stateful_host

def _auto_server():
    return ServerConfig(
        ssh_user="root", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
    )

def _staged_files(host):
    written = {}
    for c in host.put_file.call_args_list:
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[c.kwargs.get("remote_filename", "")] = bio.getvalue().decode("utf-8")
    return written

# %% pts/tests/test_auto_docker.pct.py 22
def test_deploy_auto_remote_detection_and_register():
    """Git-sourced deploy_auto detects the runtime via remote indicator probes,
    builds the image, and registers method=auto with the detected runtime."""
    host = _stateful_host()

    with patch("appgarden.auto_docker.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        deploy_auto(_auto_server(), "autoapp", "https://github.com/x/y.git",
                    "npm start", "auto.apps.example.com")

    entry = host._state["garden"]["apps"]["autoapp"]
    assert entry["method"] == "auto"
    # First indicator probe (package.json) succeeds against the mock -> nodejs
    assert entry["auto_detected_runtime"] == "nodejs"
    assert host._state["ports"]["allocated"] == {"10000": "autoapp"}

    cmds = [c.kwargs.get("command", "") for c in host.run_shell_command.call_args_list]
    assert any("git clone" in c for c in cmds)
    assert any("docker build -t appgarden-autoapp" in c for c in cmds)

    written = _staged_files(host)
    dockerfiles = [v for k, v in written.items() if k.endswith("/Dockerfile")]
    assert dockerfiles and "FROM node:22" in dockerfiles[0]
    assert "npm start" in dockerfiles[0]

# %% pts/tests/test_auto_docker.pct.py 23
def test_deploy_auto_local_detection(tmp_path):
    """A local source detects the runtime from local files before uploading."""
    (tmp_path / "requirements.txt").write_text("flask\n")
    host = _stateful_host()

    with patch("appgarden.auto_docker.ssh_connect") as mock_connect, \
         patch("appgarden.auto_docker.upload_source", return_value="local"):
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        deploy_auto(_auto_server(), "pyapp", str(tmp_path),
                    "python app.py", "py.apps.example.com")

    entry = host._state["garden"]["apps"]["pyapp"]
    assert entry["auto_detected_runtime"] == "python-pip"
    written = _staged_files(host)
    dockerfiles = [v for k, v in written.items() if k.endswith("/Dockerfile")]
    assert dockerfiles and "FROM python:3.12" in dockerfiles[0]

# %% pts/tests/test_auto_docker.pct.py 24
def test_deploy_auto_no_runtime_detected():
    """When no indicator matches (locally or remotely), deploy_auto fails
    loudly before claiming a port."""
    host = _stateful_host()
    inner = host.run_shell_command.side_effect

    def _run(command="", **kw):
        if command.startswith("test -f"):
            out = MagicMock(); out.stdout = ""; out.stderr = ""
            return (False, out)
        return inner(command=command, **kw)
    host.run_shell_command.side_effect = _run

    with patch("appgarden.auto_docker.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        with pytest.raises(RuntimeError, match="Could not detect runtime"):
            deploy_auto(_auto_server(), "mystery", "https://github.com/x/y.git",
                        "run", "m.apps.example.com")

    # Failed before the port claim: nothing leaked
    assert host._state["ports"]["allocated"] == {}
