# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_auto_docker.pct.py

__all__ = ['test_detect_go', 'test_detect_nodejs', 'test_detect_priority', 'test_detect_python_pip', 'test_detect_python_pyproject', 'test_detect_ruby', 'test_detect_rust', 'test_detect_unknown', 'test_generate_dockerfile_custom_setup', 'test_generate_dockerfile_nodejs', 'test_generate_dockerfile_python', 'test_infer_setup_nodejs', 'test_infer_setup_python']

# %% pts/tests/test_auto_docker.pct.py 3
from pathlib import Path

from appgarden.auto_docker import (
    detect_runtime, infer_setup_command, generate_dockerfile,
    Runtime, RUNTIMES,
)

# %% pts/tests/test_auto_docker.pct.py 5
def test_detect_nodejs(tmp_path):
    """Detect Node.js from package.json."""
    (tmp_path / "package.json").write_text("{}")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "nodejs"
    assert "node" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 6
def test_detect_python_pip(tmp_path):
    """Detect Python (pip) from requirements.txt."""
    (tmp_path / "requirements.txt").write_text("flask\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "python-pip"
    assert "python" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 7
def test_detect_python_pyproject(tmp_path):
    """Detect Python from pyproject.toml."""
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'myapp'\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "python"

# %% pts/tests/test_auto_docker.pct.py 8
def test_detect_go(tmp_path):
    """Detect Go from go.mod."""
    (tmp_path / "go.mod").write_text("module example.com/app\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "go"
    assert "golang" in rt.base_image

# %% pts/tests/test_auto_docker.pct.py 9
def test_detect_ruby(tmp_path):
    """Detect Ruby from Gemfile."""
    (tmp_path / "Gemfile").write_text('source "https://rubygems.org"\n')
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "ruby"

# %% pts/tests/test_auto_docker.pct.py 10
def test_detect_rust(tmp_path):
    """Detect Rust from Cargo.toml."""
    (tmp_path / "Cargo.toml").write_text("[package]\nname = 'app'\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "rust"

# %% pts/tests/test_auto_docker.pct.py 11
def test_detect_unknown(tmp_path):
    """Unknown project returns None."""
    (tmp_path / "main.c").write_text("int main() {}\n")
    rt = detect_runtime(tmp_path)
    assert rt is None

# %% pts/tests/test_auto_docker.pct.py 12
def test_detect_priority(tmp_path):
    """package.json takes priority over pyproject.toml."""
    (tmp_path / "package.json").write_text("{}")
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    rt = detect_runtime(tmp_path)
    assert rt is not None
    assert rt.name == "nodejs"

# %% pts/tests/test_auto_docker.pct.py 14
def test_infer_setup_nodejs():
    """Node.js setup is npm install."""
    rt = Runtime(name="nodejs", base_image="node:22", setup_cmd="npm install")
    assert infer_setup_command(rt) == "npm install"

# %% pts/tests/test_auto_docker.pct.py 15
def test_infer_setup_python():
    """Python setup is pip install."""
    rt = Runtime(name="python-pip", base_image="python:3.12",
                 setup_cmd="pip install -r requirements.txt")
    assert "pip install" in infer_setup_command(rt)

# %% pts/tests/test_auto_docker.pct.py 17
def test_generate_dockerfile_nodejs():
    """Generated Dockerfile for Node.js has correct structure."""
    rt = Runtime(name="nodejs", base_image="node:22",
                 setup_cmd="npm install", copy_first="package*.json")
    content = generate_dockerfile(rt, container_port=3000, cmd='["node", "server.js"]')
    assert "FROM node:22" in content
    assert "COPY package*.json ." in content
    assert "RUN npm install" in content
    assert "EXPOSE 3000" in content
    assert '["node", "server.js"]' in content

# %% pts/tests/test_auto_docker.pct.py 18
def test_generate_dockerfile_custom_setup():
    """Custom setup_cmd overrides the runtime default."""
    rt = Runtime(name="nodejs", base_image="node:22",
                 setup_cmd="npm install", copy_first="package*.json")
    content = generate_dockerfile(
        rt, container_port=8080, cmd="npm start",
        setup_cmd="npm ci --production",
    )
    assert "RUN npm ci --production" in content
    assert "npm install" not in content

# %% pts/tests/test_auto_docker.pct.py 19
def test_generate_dockerfile_python():
    """Generated Dockerfile for Python has correct structure."""
    rt = Runtime(name="python-pip", base_image="python:3.12",
                 setup_cmd="pip install -r requirements.txt",
                 copy_first="requirements.txt")
    content = generate_dockerfile(rt, container_port=5000, cmd="python app.py")
    assert "FROM python:3.12" in content
    assert "COPY requirements.txt ." in content
    assert "RUN pip install -r requirements.txt" in content
    assert "EXPOSE 5000" in content
