# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/test_server.pct.py

__all__ = ['test_caddyfile_block_migrates_legacy_unkeyed', 'test_caddyfile_block_reinit_replaces_only_that_root', 'test_caddyfile_block_two_instances_coexist', 'test_init_server_caddyfile_additive', 'test_init_server_caddyfile_idempotent', 'test_init_server_creates_state_files_when_missing', 'test_init_server_custom_app_root', 'test_init_server_host_state_dir_never_user_owned', 'test_init_server_host_state_ownership_minimal', 'test_init_server_host_state_ownership_root_group_skipped', 'test_init_server_minimal', 'test_init_server_nonroot_joins_appgarden_group_without_group_step', 'test_init_server_nonroot_uses_sudo', 'test_init_server_nonroot_writes_system_files_via_tmp', 'test_init_server_preserves_existing_state_files', 'test_init_server_reconciles_existing_app_ports', 'test_init_server_root_no_usermod', 'test_init_server_runs_expected_commands', 'test_init_server_seeds_registry_from_legacy_ports', 'test_init_server_skip_steps', 'test_init_server_writes_config_files', 'test_ping_server_failure', 'test_ping_server_success']

# %% pts/tests/test_server.pct.py 3
import json
from unittest.mock import patch, MagicMock, call

from appgarden.config import ServerConfig
from appgarden.remote import RemoteContext, PORTS_PATH, HOST_STATE_DIR
from appgarden.ports import empty_ports_state
from appgarden.server import (
    ping_server, init_server, INIT_STEPS,
    CADDYFILE_CONTENT, CADDYFILE_TEMPLATE, CADDYFILE_MARKER_BEGIN, CADDYFILE_MARKER_END,
    SSH_HARDENING_CONTENT, _ensure_caddyfile_block,
)

# %% pts/tests/test_server.pct.py 5
def _make_server():
    return ServerConfig(
        ssh_user="root", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
    )

# %% pts/tests/test_server.pct.py 6
def _make_host_mock(*, state_files_exist=True, caddyfile_content="",
                    garden_state=None, ports_state=None):
    """Create a host mock with configurable behavior for test -f and cat commands.

    Serves valid JSON for garden.json / ports.json reads (via flock-cat and
    get_file) so the init reconcile step (read garden.json → merge app ports into
    the host ports registry) works against the mock.
    """
    if garden_state is None:
        garden_state = {"apps": {}}
    if ports_state is None:
        ports_state = empty_ports_state()

    host_mock = MagicMock()
    ok_output = MagicMock()
    ok_output.stdout = ""
    fail_output = MagicMock()
    fail_output.stderr = ""

    def run_shell_side_effect(**kwargs):
        import hashlib
        cmd = kwargs.get("command", "")
        if cmd.startswith("test -f") and not state_files_exist:
            return (False, fail_output)
        if cmd.startswith("cat /etc/caddy/Caddyfile"):
            out = MagicMock(); out.stdout = caddyfile_content
            return (True, out)
        if "CAS_OK" in cmd:
            out = MagicMock(); out.stdout = "CAS_OK"
            return (True, out)
        if ("flock" in cmd and "cat" in cmd) or "sha256sum" in cmd:
            payload = json.dumps(ports_state if "ports.json" in cmd else garden_state)
            out = MagicMock()
            if "sha256sum" in cmd:
                sha = hashlib.sha256(payload.encode()).hexdigest()
                out.stdout = f"{sha}\n{payload}"
            else:
                out.stdout = payload
            return (True, out)
        return (True, ok_output)

    host_mock.run_shell_command.side_effect = run_shell_side_effect

    def _get_file(remote_filename, filename_or_io, **kw):
        data = ports_state if "ports.json" in remote_filename else garden_state
        filename_or_io.write(json.dumps(data).encode("utf-8"))
        return True

    host_mock.put_file.return_value = True
    host_mock.get_file.side_effect = _get_file
    return host_mock

# %% pts/tests/test_server.pct.py 7
def _get_written_files(host_mock):
    """Extract {path: content} from put_file calls."""
    written = {}
    for c in host_mock.put_file.call_args_list:
        remote_path = c.kwargs.get("remote_filename", "")
        bio = c.kwargs.get("filename_or_io")
        if bio:
            written[remote_path] = bio.getvalue().decode("utf-8")
    return written

# %% pts/tests/test_server.pct.py 8
def _get_cmds(host_mock):
    """Extract command strings from run_shell_command calls."""
    return [c.kwargs.get("command", c.args[0] if c.args else "")
            for c in host_mock.run_shell_command.call_args_list]

# %% pts/tests/test_server.pct.py 10
def test_ping_server_success():
    """ping_server returns True when SSH succeeds."""
    host_mock = MagicMock()
    output_mock = MagicMock()
    output_mock.stdout = "ok"
    host_mock.run_shell_command.return_value = (True, output_mock)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        assert ping_server(_make_server()) is True

# %% pts/tests/test_server.pct.py 11
def test_ping_server_failure():
    """ping_server returns False when SSH connection fails."""
    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.side_effect = Exception("Connection refused")
        assert ping_server(_make_server()) is False

# %% pts/tests/test_server.pct.py 13
def test_init_server_runs_expected_commands():
    """init_server executes the expected sequence of operations."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    cmds = _get_cmds(host_mock)

    # Should include key setup steps
    assert any("apt-get update" in c for c in cmds), "Should run apt update"
    assert any("docker-ce" in c for c in cmds), "Should install Docker"
    assert any("caddy" in c for c in cmds), "Should install Caddy"
    assert any("ufw" in c for c in cmds), "Should configure UFW"
    assert any("fail2ban" in c for c in cmds), "Should install fail2ban"
    assert any("unattended-upgrades" in c for c in cmds), "Should setup auto-updates"
    assert any("mkdir" in c for c in cmds), "Should create directories"

# %% pts/tests/test_server.pct.py 14
def test_init_server_writes_config_files():
    """init_server writes Caddyfile (with markers), SSH hardening, and state files."""
    host_mock = _make_host_mock(state_files_exist=False)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)

    # Caddyfile should contain marker block with import lines
    assert "/etc/caddy/Caddyfile" in written_files
    caddyfile = written_files["/etc/caddy/Caddyfile"]
    assert CADDYFILE_MARKER_BEGIN in caddyfile
    assert CADDYFILE_MARKER_END in caddyfile
    assert "import" in caddyfile

    assert "/etc/ssh/sshd_config.d/hardening.conf" in written_files
    assert "PasswordAuthentication no" in written_files["/etc/ssh/sshd_config.d/hardening.conf"]

    assert "/srv/appgarden/garden.json" in written_files
    # ports.json is host-global, written under HOST_STATE_DIR (not app_root)
    assert PORTS_PATH in written_files

# %% pts/tests/test_server.pct.py 16
def _make_nonroot_server():
    return ServerConfig(
        ssh_user="deploy", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
    )

# %% pts/tests/test_server.pct.py 17
def test_init_server_nonroot_uses_sudo():
    """init_server with non-root user prefixes privileged commands with sudo."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_nonroot_server())

    cmds = _get_cmds(host_mock)

    # Privileged commands should have _sudo=True; non-privileged (test -f) should not
    for c in host_mock.run_shell_command.call_args_list:
        cmd = c.kwargs.get("command", "")
        if cmd.startswith("test -f"):
            continue  # state file existence check runs without sudo
        assert c.kwargs.get("_sudo") is True, f"Expected _sudo=True for: {cmd}"

    # Should chown app root (root:appgarden when group step is enabled)
    assert any("chown" in c and "appgarden" in c for c in cmds), "Should chown app root"
    # Should add user to docker group
    assert any("usermod" in c and "docker" in c for c in cmds), "Should add user to docker group"

# %% pts/tests/test_server.pct.py 18
def test_init_server_nonroot_writes_system_files_via_tmp():
    """init_server with non-root user writes system files via /tmp/ + sudo mv."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_nonroot_server())

    # System files (/etc/) should be written via put_file with _sudo=True
    etc_calls = [c for c in host_mock.put_file.call_args_list
                 if c.kwargs.get("remote_filename", "").startswith("/etc/")]
    assert len(etc_calls) >= 2, f"Should write at least 2 system files, got: {[c.kwargs.get('remote_filename') for c in etc_calls]}"
    for c in etc_calls:
        assert c.kwargs.get("_sudo") is True, f"System file write should have _sudo=True: {c.kwargs.get('remote_filename')}"

# %% pts/tests/test_server.pct.py 19
def test_init_server_custom_app_root():
    """init_server with custom app_root uses the custom path."""
    server = ServerConfig(
        ssh_user="root", ssh_key="~/.ssh/id_rsa",
        domain="apps.example.com", host="1.2.3.4",
        app_root="/opt/myapps",
    )
    host_mock = _make_host_mock(state_files_exist=False)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(server)

    cmds = _get_cmds(host_mock)

    # Should create dirs under custom root
    assert any("/opt/myapps" in c and "mkdir" in c for c in cmds), "Should create custom root dirs"

    # Caddyfile should reference custom root within marker block
    written_files = _get_written_files(host_mock)
    assert "/etc/caddy/Caddyfile" in written_files
    caddyfile = written_files["/etc/caddy/Caddyfile"]
    assert "/opt/myapps" in caddyfile
    assert CADDYFILE_MARKER_BEGIN in caddyfile

    # garden.json is at the custom root; ports.json is host-global (box-level)
    assert "/opt/myapps/garden.json" in written_files
    assert "/opt/myapps/ports.json" not in written_files
    assert PORTS_PATH in written_files

# %% pts/tests/test_server.pct.py 21
def test_init_server_caddyfile_additive():
    """Existing Caddyfile content is preserved, block appended."""
    existing = "example.com {\n    respond \"Hello\"\n}\n"
    host_mock = _make_host_mock(caddyfile_content=existing)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)
    caddyfile = written_files["/etc/caddy/Caddyfile"]

    # Existing content preserved
    assert 'respond "Hello"' in caddyfile
    # Marker block appended
    assert CADDYFILE_MARKER_BEGIN in caddyfile
    assert CADDYFILE_MARKER_END in caddyfile
    assert "import /srv/appgarden/caddy/apps/*.caddy" in caddyfile

# %% pts/tests/test_server.pct.py 22
def test_init_server_caddyfile_idempotent():
    """Running init twice doesn't duplicate the marker block."""
    # Simulate a Caddyfile that already has the marker block
    existing = (
        "example.com {\n    respond \"Hello\"\n}\n\n"
        f"{CADDYFILE_MARKER_BEGIN}\n"
        "import /srv/appgarden/caddy/apps/*.caddy\n"
        "import /srv/appgarden/caddy/tunnels/*.caddy\n"
        f"{CADDYFILE_MARKER_END}\n"
    )
    host_mock = _make_host_mock(caddyfile_content=existing)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)
    caddyfile = written_files["/etc/caddy/Caddyfile"]

    # Should have exactly one marker block
    assert caddyfile.count(CADDYFILE_MARKER_BEGIN) == 1
    assert caddyfile.count(CADDYFILE_MARKER_END) == 1
    # Existing content still preserved
    assert 'respond "Hello"' in caddyfile

# %% pts/tests/test_server.pct.py 24
def _run_ensure_block(initial, app_roots):
    """Drive `_ensure_caddyfile_block` for each app_root against an in-memory
    Caddyfile (initial=None means the file doesn't exist yet). Returns the final
    file content."""
    file = {"content": initial}

    def fake_cat(host, cmd, ctx=None):
        if file["content"] is None:
            raise RuntimeError("file not found")
        return file["content"]

    def fake_write(host, path, content, ctx=None):
        file["content"] = content

    with patch("appgarden.server.run_sudo_command", side_effect=fake_cat), \
         patch("appgarden.server.write_system_file", side_effect=fake_write):
        for root in app_roots:
            ctx = RemoteContext(app_root=root)
            _ensure_caddyfile_block(None, CADDYFILE_TEMPLATE.format(app_root=root), ctx=ctx)
    return file["content"]

# %% pts/tests/test_server.pct.py 25
def test_caddyfile_block_two_instances_coexist():
    """Two app_roots keep independent keyed blocks; the second init keeps the first."""
    content = _run_ensure_block(None, ["/srv/appgarden", "/srv/appgarden-proto"])
    # Both instances' import lines survive
    assert "import /srv/appgarden/caddy/apps/*.caddy" in content
    assert "import /srv/appgarden-proto/caddy/apps/*.caddy" in content
    # Two distinct keyed begin markers
    assert "# BEGIN APPGARDEN MANAGED BLOCK: /srv/appgarden\n" in content
    assert "# BEGIN APPGARDEN MANAGED BLOCK: /srv/appgarden-proto\n" in content
    assert content.count(CADDYFILE_MARKER_BEGIN) == 2

# %% pts/tests/test_server.pct.py 26
def test_caddyfile_block_reinit_replaces_only_that_root():
    """Re-running init for one root replaces only its block, leaving the other intact."""
    first = _run_ensure_block(None, ["/srv/appgarden", "/srv/appgarden-proto"])
    again = _run_ensure_block(first, ["/srv/appgarden"])
    assert again.count("# BEGIN APPGARDEN MANAGED BLOCK: /srv/appgarden\n") == 1
    assert again.count("# BEGIN APPGARDEN MANAGED BLOCK: /srv/appgarden-proto\n") == 1
    assert "import /srv/appgarden-proto/caddy/apps/*.caddy" in again

# %% pts/tests/test_server.pct.py 27
def test_caddyfile_block_migrates_legacy_unkeyed():
    """A pre-existing legacy un-keyed block is migrated in place for the default root."""
    legacy = (
        'example.com {\n    respond "Hi"\n}\n\n'
        f"{CADDYFILE_MARKER_BEGIN}\n"
        "import /srv/appgarden/caddy/apps/*.caddy\n"
        "import /srv/appgarden/caddy/tunnels/*.caddy\n"
        f"{CADDYFILE_MARKER_END}\n"
    )
    content = _run_ensure_block(legacy, ["/srv/appgarden"])
    # Legacy block replaced in place (not duplicated) with the keyed form
    assert "# BEGIN APPGARDEN MANAGED BLOCK: /srv/appgarden" in content
    assert content.count(CADDYFILE_MARKER_BEGIN) == 1
    # Foreign content preserved
    assert 'respond "Hi"' in content

# %% pts/tests/test_server.pct.py 29
def test_init_server_preserves_existing_state_files():
    """Existing garden.json is not overwritten."""
    host_mock = _make_host_mock(state_files_exist=True)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)
    # Existing state files are preserved (not rewritten). garden.json is empty,
    # so the host ports registry needs no reconcile write either.
    assert "/srv/appgarden/garden.json" not in written_files
    assert PORTS_PATH not in written_files

# %% pts/tests/test_server.pct.py 30
def test_init_server_creates_state_files_when_missing():
    """Missing state files are created (garden.json per-garden, ports.json host-global)."""
    host_mock = _make_host_mock(state_files_exist=False)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)
    assert "/srv/appgarden/garden.json" in written_files
    assert PORTS_PATH in written_files

# %% pts/tests/test_server.pct.py 31
def test_init_server_reconciles_existing_app_ports():
    """init merges this garden's already-deployed app ports into the host registry."""
    garden = {"apps": {"web": {"port": 10000}, "api": {"port": 10005}}}
    host_mock = _make_host_mock(state_files_exist=True, garden_state=garden,
                                ports_state=empty_ports_state())

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    # The reconciled host registry is written back with both app ports.
    written_files = _get_written_files(host_mock)
    # update_ports_state_locked stages a unique tmp file then CAS-mv's it into place
    tmp = next((c for p, c in written_files.items() if p.startswith(PORTS_PATH)), None)
    assert tmp is not None, f"expected a host ports.json write, got {list(written_files)}"
    state = json.loads(tmp)
    assert state["allocated"] == {"10000": "web", "10005": "api"}
    assert state["next_port"] == 10006

# %% pts/tests/test_server.pct.py 32
def test_init_server_seeds_registry_from_legacy_ports():
    """Creating the host registry seeds it from the legacy ports.json, preserving
    reservations not in garden.json (e.g. an active tunnel's port)."""
    # Host registry absent (state_files_exist=False); legacy ports.json holds a
    # live tunnel reservation that garden.json doesn't know about.
    legacy = {"next_port": 10061, "allocated": {"10060": "tunnel-abc"}}
    host_mock = _make_host_mock(state_files_exist=False, ports_state=legacy)

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    written_files = _get_written_files(host_mock)
    seeded = json.loads(written_files[PORTS_PATH])
    assert seeded["allocated"].get("10060") == "tunnel-abc"
    assert seeded["next_port"] == 10061

# %% pts/tests/test_server.pct.py 34
def test_init_server_skip_steps():
    """skip={'docker', 'firewall'} skips those commands."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server(), skip={"docker", "firewall"})

    cmds = _get_cmds(host_mock)

    # Skipped steps should not appear
    assert not any("docker-ce" in c for c in cmds), "Docker install should be skipped"
    assert not any("ufw" in c for c in cmds), "UFW should be skipped"

    # Non-skipped steps should still run
    assert any("apt-get update" in c for c in cmds), "Should still run apt update"
    assert any("caddy" in c for c in cmds), "Should still install Caddy"
    assert any("mkdir" in c for c in cmds), "Should still create directories"

# %% pts/tests/test_server.pct.py 35
def test_init_server_minimal():
    """skip=INIT_STEPS only runs essential steps."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server(), skip=set(INIT_STEPS))

    cmds = _get_cmds(host_mock)

    # All optional steps should be skipped
    assert not any("apt-get update" in c and "upgrade" in c for c in cmds), "System update should be skipped"
    assert not any("docker-ce" in c for c in cmds), "Docker install should be skipped"
    assert not any("ufw" in c for c in cmds), "UFW should be skipped"
    assert not any("fail2ban" in c for c in cmds), "fail2ban should be skipped"
    assert not any("unattended-upgrades" in c for c in cmds), "unattended-upgrades should be skipped"

    # Essential steps should still run
    assert any("mkdir" in c for c in cmds), "Should create directories"
    assert any("caddy" in c and "systemctl" in c for c in cmds), "Should start Caddy"

    # Caddyfile should still be written (essential)
    written_files = _get_written_files(host_mock)
    assert "/etc/caddy/Caddyfile" in written_files

    # SSH hardening should NOT be written (optional)
    assert "/etc/ssh/sshd_config.d/hardening.conf" not in written_files

# %% pts/tests/test_server.pct.py 37
def _host_state_ownership_cmds(cmds):
    """Commands that set the essential HOST_STATE_DIR ownership."""
    return [c for c in cmds
            if "groupadd -f appgarden" in c
            and f"chown -R root:appgarden {HOST_STATE_DIR}" in c
            and "g+rwX" in c and "g+s" in c]

# %% pts/tests/test_server.pct.py 38
def test_init_server_host_state_ownership_root_group_skipped():
    """A root init with the group step skipped (the adu-apps case) still sets
    HOST_STATE_DIR to root:appgarden group-writable setgid."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server(), skip={"group"})

    cmds = _get_cmds(host_mock)
    assert len(_host_state_ownership_cmds(cmds)) == 1, \
        f"HOST_STATE_DIR ownership must be set even with group step skipped; cmds: {cmds}"
    # The skipped group step must not run its per-garden app_root sharing.
    assert not any("chgrp -R appgarden" in c for c in cmds)

# %% pts/tests/test_server.pct.py 39
def test_init_server_host_state_ownership_minimal():
    """The HOST_STATE_DIR ownership step is essential: it runs even with all
    optional steps skipped."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server(), skip=set(INIT_STEPS))

    cmds = _get_cmds(host_mock)
    assert len(_host_state_ownership_cmds(cmds)) == 1

# %% pts/tests/test_server.pct.py 40
def test_init_server_host_state_dir_never_user_owned():
    """A non-root init with the group step skipped chowns app_root to the
    ssh_user but leaves HOST_STATE_DIR root:appgarden (shared, box-global)."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_nonroot_server(), skip={"group"})

    cmds = _get_cmds(host_mock)
    assert len(_host_state_ownership_cmds(cmds)) == 1
    # app_root is chowned to the deploy user...
    assert any("chown -R deploy:deploy" in c and "/srv/appgarden" in c for c in cmds)
    # ...but never HOST_STATE_DIR.
    assert not any("deploy:deploy" in c and HOST_STATE_DIR in c for c in cmds)

# %% pts/tests/test_server.pct.py 41
def test_init_server_nonroot_joins_appgarden_group_without_group_step():
    """A non-root ssh_user is added to the appgarden group even when the
    per-garden group step is skipped — it needs the group to write the shared
    host ports registry."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_nonroot_server(), skip={"group"})

    cmds = _get_cmds(host_mock)
    assert any("usermod -aG appgarden deploy" in c for c in cmds), \
        f"non-root user must join appgarden group even without the group step; cmds: {cmds}"

# %% pts/tests/test_server.pct.py 42
def test_init_server_root_no_usermod():
    """A root init never needs a usermod into the appgarden group."""
    host_mock = _make_host_mock()

    with patch("appgarden.server.ssh_connect") as mock_connect:
        mock_connect.return_value.__enter__ = MagicMock(return_value=host_mock)
        mock_connect.return_value.__exit__ = MagicMock(return_value=False)
        init_server(_make_server())

    cmds = _get_cmds(host_mock)
    assert not any("usermod -aG appgarden" in c for c in cmds)
