# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/test_server_init.pct.py

__all__ = ['pytestmark', 'test_caddy_config', 'test_caddy_installed', 'test_directory_structure', 'test_docker_installed', 'test_garden_json', 'test_ports_json', 'test_ufw_enabled']

# %% pts/tests/integration/test_server_init.pct.py 3
import json

import pytest

from appgarden.remote import ssh_connect, run_remote_command, read_remote_file

# %% pts/tests/integration/test_server_init.pct.py 4
pytestmark = pytest.mark.integration

# %% pts/tests/integration/test_server_init.pct.py 5
def test_docker_installed(initialized_server):
    """Docker is installed and running."""
    with ssh_connect(initialized_server) as host:
        out = run_remote_command(host, "docker --version")
        assert "Docker" in out

# %% pts/tests/integration/test_server_init.pct.py 6
def test_caddy_installed(initialized_server):
    """Caddy is installed and running."""
    with ssh_connect(initialized_server) as host:
        out = run_remote_command(host, "caddy version")
        assert "v" in out

# %% pts/tests/integration/test_server_init.pct.py 7
def test_caddy_config(initialized_server):
    """Root Caddyfile contains appgarden managed block with imports."""
    with ssh_connect(initialized_server) as host:
        content = read_remote_file(host, "/etc/caddy/Caddyfile")
        assert "# BEGIN APPGARDEN MANAGED BLOCK" in content
        assert "# END APPGARDEN MANAGED BLOCK" in content
        assert "/srv/appgarden/caddy/apps/*.caddy" in content
        assert "/srv/appgarden/caddy/tunnels/*.caddy" in content

# %% pts/tests/integration/test_server_init.pct.py 8
def test_ufw_enabled(initialized_server):
    """UFW is active and allows SSH/HTTP/HTTPS."""
    with ssh_connect(initialized_server) as host:
        out = run_remote_command(host, "ufw status")
        assert "active" in out.lower()

# %% pts/tests/integration/test_server_init.pct.py 9
def test_directory_structure(initialized_server):
    """AppGarden directory structure exists."""
    with ssh_connect(initialized_server) as host:
        dirs = [
            "/srv/appgarden/apps",
            "/srv/appgarden/caddy/apps",
            "/srv/appgarden/caddy/tunnels",
            "/srv/appgarden/tunnels",
        ]
        for d in dirs:
            out = run_remote_command(host, f"test -d {d} && echo yes")
            assert "yes" in out, f"Directory {d} missing"

# %% pts/tests/integration/test_server_init.pct.py 10
def test_garden_json(initialized_server):
    """garden.json is initialised."""
    with ssh_connect(initialized_server) as host:
        raw = read_remote_file(host, "/srv/appgarden/garden.json")
        data = json.loads(raw)
        assert "apps" in data
        assert data["apps"] == {}

# %% pts/tests/integration/test_server_init.pct.py 11
def test_ports_json(initialized_server):
    """ports.json is initialised."""
    with ssh_connect(initialized_server) as host:
        raw = read_remote_file(host, "/srv/appgarden/ports.json")
        data = json.loads(raw)
        assert "next_port" in data
        assert "allocated" in data
