# AUTOGENERATED! DO NOT EDIT! File to edit: pts/appgarden/00_config.pct.py

__all__ = ['AppGardenConfig', 'ServerConfig', 'config_dir', 'config_path', 'get_server', 'load_config', 'resolve_host', 'save_config']

# %% pts/appgarden/00_config.pct.py 3
import os
import subprocess
import tomllib
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

import tomli_w

# %% pts/appgarden/00_config.pct.py 5
@dataclass
class ServerConfig:
    """Configuration for a single server."""
    ssh_user: str
    ssh_key: str          # path, ~ expanded on use
    domain: str
    host: str | None = None
    hcloud_name: str | None = None
    hcloud_context: str | None = None
    app_root: str | None = None  # default None → "/srv/appgarden"

# %% pts/appgarden/00_config.pct.py 6
@dataclass
class AppGardenConfig:
    """Top-level AppGarden configuration."""
    default_server: str | None = None
    servers: dict[str, ServerConfig] = field(default_factory=dict)
    defaults: dict[str, Any] = field(default_factory=dict)

# %% pts/appgarden/00_config.pct.py 8
def config_dir() -> Path:
    """Return the AppGarden config directory, creating it if needed."""
    d = Path.home() / ".config" / "appgarden"
    d.mkdir(parents=True, exist_ok=True)
    return d

# %% pts/appgarden/00_config.pct.py 9
def config_path() -> Path:
    """Return the path to the config file."""
    return config_dir() / "config.toml"

# %% pts/appgarden/00_config.pct.py 11
def load_config(path: Path | None = None) -> AppGardenConfig:
    """Load configuration from TOML. Returns empty config if file is missing."""
    p = path or config_path()
    if not p.exists():
        return AppGardenConfig()

    with open(p, "rb") as f:
        raw = tomllib.load(f)

    valid_keys = {f.name for f in ServerConfig.__dataclass_fields__.values()}
    servers = {}
    for name, sdata in raw.get("servers", {}).items():
        unknown = set(sdata) - valid_keys
        if unknown:
            raise ValueError(
                f"Unknown key(s) in [servers.{name}]: {', '.join(sorted(unknown))}. "
                f"Valid keys: {', '.join(sorted(valid_keys))}"
            )
        servers[name] = ServerConfig(**sdata)

    return AppGardenConfig(
        default_server=raw.get("default_server"),
        servers=servers,
        defaults=dict(raw.get("defaults", {})),
    )

# %% pts/appgarden/00_config.pct.py 12
def save_config(config: AppGardenConfig, path: Path | None = None) -> None:
    """Write configuration to TOML."""
    p = path or config_path()
    p.parent.mkdir(parents=True, exist_ok=True)

    raw: dict = {}
    if config.default_server is not None:
        raw["default_server"] = config.default_server

    if config.defaults:
        raw["defaults"] = dict(config.defaults)

    if config.servers:
        raw["servers"] = {}
        for name, srv in config.servers.items():
            d = asdict(srv)
            # Drop None values for cleaner TOML
            raw["servers"][name] = {k: v for k, v in d.items() if v is not None}

    with open(p, "wb") as f:
        tomli_w.dump(raw, f)
    os.chmod(p, 0o600)

# %% pts/appgarden/00_config.pct.py 14
def resolve_host(server: ServerConfig) -> str:
    """Resolve the server's IP address.

    Returns ``host`` directly if set, otherwise calls ``hcloud`` to look up
    the IP from the server's ``hcloud_name`` and ``hcloud_context``.
    """
    if server.host:
        return server.host

    if not server.hcloud_name or not server.hcloud_context:
        raise ValueError("Server must have either 'host' or both 'hcloud_name' and 'hcloud_context'")

    result = subprocess.run(
        ["hcloud", "--context", server.hcloud_context, "server", "ip", server.hcloud_name],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()

# %% pts/appgarden/00_config.pct.py 16
def get_server(config: AppGardenConfig, name: str | None = None) -> tuple[str, ServerConfig]:
    """Look up a server by name, falling back to the default server.

    Returns a ``(name, ServerConfig)`` tuple.
    """
    if name is None:
        name = config.default_server
    if name is None:
        raise ValueError("No server specified and no default server configured")
    if name not in config.servers:
        raise ValueError(f"Server '{name}' not found in configuration")
    return name, config.servers[name]
