# AUTOGENERATED! DO NOT EDIT! File to edit: pts/appgarden/04_server.pct.py

__all__ = ['CADDYFILE_CONTENT', 'CADDYFILE_MARKER_BEGIN', 'CADDYFILE_MARKER_END', 'CADDYFILE_TEMPLATE', 'INIT_STEPS', 'INIT_STEPS_OFF', 'SSH_HARDENING_CONTENT', 'TEMPLATES_DIR', 'console', 'init_server', 'ping_server']

# %% pts/appgarden/04_server.pct.py 3
import json
import shlex
from pathlib import Path

from rich.console import Console

from .config import ServerConfig, resolve_host
from .ports import empty_ports_state, merge_allocations
from .remote import (
    APPGARDEN_ROOT, GARDEN_STATE_PATH, PORTS_PATH, HOST_STATE_DIR,
    PRIVILEGED_HELPER_PATH,
    RemoteContext, make_remote_context,
    ssh_connect, run_remote_command, read_remote_file, write_remote_file,
    run_sudo_command, write_system_file,
    read_garden_state, read_ports_state_locked, write_ports_state_locked,
    garden_state_path, ports_path,
)

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"

console = Console()

# %% pts/appgarden/04_server.pct.py 5
def ping_server(server: ServerConfig) -> bool:
    """Test SSH connectivity to a server. Returns True if reachable."""
    try:
        with ssh_connect(server) as host:
            run_remote_command(host, "echo ok")
        return True
    except Exception:
        return False

# %% pts/appgarden/04_server.pct.py 7
CADDYFILE_TEMPLATE = """\
import {app_root}/caddy/apps/*.caddy
import {app_root}/caddy/tunnels/*.caddy
"""

# Keep for backwards compat in tests
CADDYFILE_CONTENT = CADDYFILE_TEMPLATE.format(app_root=APPGARDEN_ROOT)

CADDYFILE_MARKER_BEGIN = "# BEGIN APPGARDEN MANAGED BLOCK"
CADDYFILE_MARKER_END = "# END APPGARDEN MANAGED BLOCK"

INIT_STEPS = {"update", "docker", "caddy", "firewall", "ssh", "fail2ban", "upgrades", "group"}
INIT_STEPS_OFF = {"firewall", "ssh", "fail2ban", "group"}

SSH_HARDENING_CONTENT = """\
PasswordAuthentication no
MaxAuthTries 3
X11Forwarding no
"""

# %% pts/appgarden/04_server.pct.py 8
def _run(host, cmd: str, label: str, ctx: RemoteContext | None = None, timeout: int = 300) -> None:
    """Run a command on the remote, printing a status label. Uses sudo if needed."""
    console.print(f"  [dim]{label}[/dim]")
    run_sudo_command(host, cmd, ctx=ctx, timeout=timeout)

# %% pts/appgarden/04_server.pct.py 9
def _caddyfile_markers(app_root: str) -> tuple[str, str]:
    """Return the per-``app_root`` managed-block marker lines.

    Keying the markers by ``app_root`` lets multiple AppGarden instances on one
    host keep independent managed blocks in ``/etc/caddy/Caddyfile`` — running
    ``server init`` for one instance no longer clobbers another's import lines.
    """
    return (
        f"{CADDYFILE_MARKER_BEGIN}: {app_root}",
        f"{CADDYFILE_MARKER_END}: {app_root}",
    )

# %% pts/appgarden/04_server.pct.py 10
def _find_managed_block(current: str, begin: str, end: str) -> tuple[int, int] | None:
    """Locate the managed block delimited by exact *begin*/*end* marker lines.

    Returns the ``(start, stop)`` character span covering the begin-marker line
    through the newline after the end-marker line, or ``None`` if absent. Matching
    is on whole stripped lines so a keyed marker (``... BLOCK: /srv/x``) is never
    confused with the legacy un-keyed marker (``... BLOCK``), of which it is a
    substring.
    """
    lines = current.splitlines(keepends=True)
    begin_idx = None
    offset = 0
    starts = []
    for line in lines:
        starts.append(offset)
        offset += len(line)
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == begin:
            begin_idx = i
        elif stripped == end and begin_idx is not None:
            return starts[begin_idx], starts[i] + len(lines[i])
    return None

# %% pts/appgarden/04_server.pct.py 11
def _ensure_caddyfile_block(host, block_content: str, ctx: RemoteContext | None = None) -> None:
    """Add or update this instance's managed block in /etc/caddy/Caddyfile.

    The block is keyed by ``ctx.app_root`` so several AppGarden instances coexist
    in one Caddyfile.  If the file doesn't exist or has no matching block, the
    block is appended; if it exists, the content between this instance's markers
    is replaced.  Content outside the markers (including other instances' blocks)
    is never modified.  For the default ``app_root`` a pre-existing legacy
    un-keyed block is migrated in place.
    """
    caddyfile_path = "/etc/caddy/Caddyfile"
    app_root = ctx.app_root if ctx is not None else APPGARDEN_ROOT
    begin, end = _caddyfile_markers(app_root)
    managed_block = f"{begin}\n{block_content}{end}\n"

    # Try to read existing Caddyfile
    try:
        current = run_sudo_command(host, f"cat {shlex.quote(caddyfile_path)}", ctx=ctx)
    except RuntimeError:
        # File doesn't exist yet — just write the block
        write_system_file(host, caddyfile_path, managed_block, ctx=ctx)
        return

    # Find this instance's keyed block; fall back to a legacy un-keyed block when
    # migrating the default instance from a pre-multi-instance Caddyfile.
    span = _find_managed_block(current, begin, end)
    if span is None and app_root == APPGARDEN_ROOT:
        span = _find_managed_block(current, CADDYFILE_MARKER_BEGIN, CADDYFILE_MARKER_END)

    if span is not None:
        start, stop = span
        new_content = current[:start] + managed_block + current[stop:]
    else:
        # Append block to end
        new_content = current.rstrip("\n") + "\n\n" + managed_block if current.strip() else managed_block

    write_system_file(host, caddyfile_path, new_content, ctx=ctx)

# %% pts/appgarden/04_server.pct.py 12
def init_server(server: ServerConfig, *, skip: set[str] | None = None) -> None:
    """Initialise a remote server for AppGarden use.

    Optional steps can be skipped via the ``skip`` parameter.  Valid step
    names are defined in ``INIT_STEPS``: update, docker, caddy, firewall,
    ssh, fail2ban, upgrades.  Essential steps (directory structure, Caddyfile
    block, state files, service starts) always run.
    """
    skip = skip or set()
    ctx = make_remote_context(server)
    console.print(f"[bold]Initialising server[/bold] ({resolve_host(server)})")

    with ssh_connect(server) as host:
        # 1. System updates (optional)
        if "update" not in skip:
            _run(host, "apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq",
                 "Updating system packages", ctx=ctx)

        # 2. Install Docker CE (optional)
        if "docker" not in skip:
            _run(host,
                 "apt-get install -y -qq ca-certificates curl gnupg && "
                 "install -m 0755 -d /etc/apt/keyrings && "
                 ". /etc/os-release && "
                 "curl -fsSL https://download.docker.com/linux/$ID/gpg -o /etc/apt/keyrings/docker.asc && "
                 "chmod a+r /etc/apt/keyrings/docker.asc && "
                 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] '
                 'https://download.docker.com/linux/$ID $VERSION_CODENAME stable" '
                 "> /etc/apt/sources.list.d/docker.list && "
                 "apt-get update -qq && "
                 "apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin",
                 "Installing Docker CE", ctx=ctx)

        # 3. Install Caddy (optional)
        if "caddy" not in skip:
            _run(host,
                 "apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl && "
                 "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | "
                 "gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && "
                 "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | "
                 "tee /etc/apt/sources.list.d/caddy-stable.list && "
                 "apt-get update -qq && "
                 "apt-get install -y -qq caddy",
                 "Installing Caddy", ctx=ctx)

        # 4. Configure Caddyfile (essential, but additive)
        caddyfile_content = CADDYFILE_TEMPLATE.format(app_root=ctx.app_root)
        _ensure_caddyfile_block(host, caddyfile_content, ctx=ctx)
        console.print("  [dim]Configured Caddyfile[/dim]")

        # 5. UFW firewall (optional)
        if "firewall" not in skip:
            _run(host,
                 "apt-get install -y -qq ufw && "
                 "ufw default deny incoming && "
                 "ufw default allow outgoing && "
                 "ufw allow ssh && "
                 "ufw allow http && "
                 "ufw allow https && "
                 "ufw --force enable",
                 "Configuring firewall (UFW)", ctx=ctx)

        # 6. SSH hardening (optional)
        if "ssh" not in skip:
            write_system_file(host, "/etc/ssh/sshd_config.d/hardening.conf", SSH_HARDENING_CONTENT, ctx=ctx)
            _run(host, "systemctl reload sshd", "Hardening SSH", ctx=ctx)

        # 7. fail2ban (optional)
        if "fail2ban" not in skip:
            _run(host, "apt-get install -y -qq fail2ban && systemctl enable fail2ban && systemctl start fail2ban",
                 "Installing fail2ban", ctx=ctx)

        # 8. unattended-upgrades (optional)
        if "upgrades" not in skip:
            _run(host, "apt-get install -y -qq unattended-upgrades && "
                 "dpkg-reconfigure -f noninteractive unattended-upgrades",
                 "Enabling unattended-upgrades", ctx=ctx)

        # 9. AppGarden directory structure (essential, idempotent)
        # HOST_STATE_DIR holds the host-level shared ports registry (one per box,
        # used by every garden); the rest is per-``app_root``.
        app_root = ctx.app_root
        dirs = [
            f"{app_root}/apps",
            f"{app_root}/caddy/apps",
            f"{app_root}/caddy/tunnels",
            f"{app_root}/tunnels",
            HOST_STATE_DIR,
        ]
        _run(host, f"mkdir -p {' '.join(dirs)}", "Creating directory structure", ctx=ctx)

        # 10. Create appgarden group (optional, opt-in)
        if "group" not in skip:
            _run(host,
                 f"groupadd -f appgarden && "
                 f"chgrp -R appgarden {app_root} {HOST_STATE_DIR} && "
                 f"chmod -R g+rwX {app_root} {HOST_STATE_DIR} && "
                 f"find {app_root} {HOST_STATE_DIR} -type d -exec chmod g+s {{}} +",
                 "Creating appgarden group", ctx=ctx)

        # 10b. Install privileged wrapper and sudoers entry (essential)
        wrapper_src = TEMPLATES_DIR / "appgarden-privileged"
        wrapper_content = wrapper_src.read_text()
        write_system_file(host, PRIVILEGED_HELPER_PATH, wrapper_content, ctx=ctx)
        _run(host, f"chmod 755 {PRIVILEGED_HELPER_PATH} && chown root:root {PRIVILEGED_HELPER_PATH}",
             "Installing privileged wrapper", ctx=ctx)
        sudoers_line = f"%appgarden ALL=(ALL) NOPASSWD: {PRIVILEGED_HELPER_PATH}\n"
        write_system_file(host, "/etc/sudoers.d/appgarden", sudoers_line, ctx=ctx)
        _run(host, "chmod 440 /etc/sudoers.d/appgarden",
             "Configuring sudoers for appgarden", ctx=ctx)

        # 11. Set app root ownership for deploy users (essential)
        if "group" not in skip:
            _run(host, f"chown -R root:appgarden {app_root} {HOST_STATE_DIR}",
                 "Setting app root ownership", ctx=ctx)
            if ctx.needs_sudo:
                _run(host, f"usermod -aG appgarden {server.ssh_user}",
                     "Adding user to appgarden group", ctx=ctx)
        elif ctx.needs_sudo:
            _run(host, f"chown -R {server.ssh_user}:{server.ssh_user} {app_root} {HOST_STATE_DIR}",
                 "Setting app root ownership", ctx=ctx)
        if ctx.needs_sudo and "docker" not in skip:
            _run(host, f"usermod -aG docker {server.ssh_user}",
                 "Adding user to docker group", ctx=ctx)

        # 11. Initialise state files (essential)
        # garden.json is per-garden — create only if missing so existing app
        # registries are preserved.
        try:
            run_remote_command(host, f"test -f {shlex.quote(garden_state_path(ctx))}")
            console.print("  [dim]garden.json already exists, preserving[/dim]")
        except RuntimeError:
            write_remote_file(host, garden_state_path(ctx), json.dumps({"apps": {}}, indent=2))
            console.print("  [dim]Initialised garden.json[/dim]")

        # ports.json is host-global (one shared registry per box). Ensure it
        # exists, then reconcile this garden's already-deployed app ports into it.
        # Running init on each garden migrates them all into the single registry;
        # reconciling from garden.json (the authoritative per-garden state) is
        # idempotent, so this is safe to run on every init.
        try:
            run_remote_command(host, f"test -f {shlex.quote(ports_path())}")
        except RuntimeError:
            # First creation of the host registry on this box: seed it from this
            # garden's legacy per-app_root ports.json (pre-shared-registry). That
            # captures reservations that aren't in garden.json — notably active
            # tunnel ports — so a later deploy can't collide with them.
            seed = empty_ports_state()
            legacy_ports_path = f"{ctx.app_root}/ports.json"
            try:
                legacy = json.loads(read_remote_file(host, legacy_ports_path))
                seed = merge_allocations(
                    seed, {int(p): n for p, n in legacy.get("allocated", {}).items()})
            except (FileNotFoundError, RuntimeError, json.JSONDecodeError):
                pass
            write_remote_file(host, ports_path(), json.dumps(seed, indent=2))
            console.print("  [dim]Initialised host ports registry[/dim]")
        garden = read_garden_state(host, ctx=ctx)
        allocations = {entry["port"]: name
                       for name, entry in garden.get("apps", {}).items()
                       if entry.get("port") is not None}
        if allocations:
            ports = read_ports_state_locked(host)
            ports = merge_allocations(ports, allocations)
            write_ports_state_locked(host, ports)
            console.print(f"  [dim]Reconciled {len(allocations)} app port(s) into host registry[/dim]")

        # 12. Start Docker (conditional on docker being present)
        try:
            run_sudo_command(host, "command -v docker", ctx=ctx)
            _run(host, "systemctl enable docker && systemctl start docker", "Starting Docker", ctx=ctx)
        except RuntimeError:
            pass

        # 13. Start Caddy (essential)
        _run(host, "systemctl enable caddy && systemctl restart caddy", "Starting Caddy", ctx=ctx)

    console.print("[bold green]Server initialised successfully.[/bold green]")
